package org.tsicoop.dpdpcms.service.v1.dpia;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;

/**
 * Parity test: the ported Java {@link DpiaEngine} MUST produce the same DPIA report as the Python
 * PoC ({@code engine_source/dpia_report.py}) for a known input.
 *
 * <p>The golden file {@code src/test/resources/dpdpa/dpia-golden.json} was generated by running the
 * Python engine on the EXACT input this test rebuilds in Java (3 activities exercising every gap
 * path + a FiduciaryContext with mixed governance flags). We compare parsed JSON trees (order- and
 * whitespace-independent) so a match proves the Java logic — citations, gap codes, status roll-up,
 * remediations, 11-section structure — is byte-equivalent to the de-risked Python.
 */
class DpiaEngineParityTest {

  private static final ObjectMapper MAPPER = new ObjectMapper();

  /** Rebuild the EXACT input used to generate the golden Python output. */
  private static List<Map<String, Object>> knownInput() {
    List<Map<String, Object>> ropa = new ArrayList<>();

    // 1) consent basis, has mechanism, retention set, categories -> compliant
    Map<String, Object> a1 = new LinkedHashMap<>();
    a1.put("activity_name", "Contacts01");
    a1.put("purpose", "crm");
    a1.put("legal_basis", "consent");
    a1.put("data_categories", Arrays.asList("email", "phone", "name"));
    a1.put("data_subject_categories", Arrays.asList("customers"));
    a1.put("retention_period_days", 365);
    a1.put("retention_start_event", "collection");
    a1.put("consent_mechanism", "web_form");
    a1.put("security_measures", "encryption at rest");
    a1.put("is_special_category", false);
    a1.put("status", "active");
    ropa.add(a1);

    // 2) no legal basis, no retention, no categories -> non_compliant (blocking)
    Map<String, Object> a2 = new LinkedHashMap<>();
    a2.put("activity_name", "OrphanTable");
    a2.put("purpose", "unknown");
    a2.put("legal_basis", "");
    a2.put("data_categories", new ArrayList<>());
    a2.put("status", "active");
    ropa.add(a2);

    // 3) legitimate_use, special category, children in subjects, cross-border, processor
    Map<String, Object> a3 = new LinkedHashMap<>();
    a3.put("activity_name", "Analytics_Minors");
    a3.put("purpose", "analytics");
    a3.put("legal_basis", "legitimate_use");
    a3.put("data_categories", Arrays.asList("age", "device_id"));
    a3.put("data_subject_categories", Arrays.asList("children", "under_18 visitors"));
    a3.put("retention_period_days", 90);
    a3.put("cross_border_transfers", Arrays.asList("us-analytics-saas"));
    Map<String, Object> proc = new LinkedHashMap<>();
    proc.put("name", "GA");
    a3.put("processors", Arrays.asList(proc));
    a3.put("is_special_category", true);
    a3.put("status", "active");
    ropa.add(a3);

    return ropa;
  }

  private static FiduciaryContext knownContext() {
    return FiduciaryContext.builder()
        .fiduciaryRef("...ab12cd")
        .isSignificantDataFiduciary(true)
        .hasDpo(false)
        .hasGrievanceMechanism(false)
        .hasAuditor(true)
        .hasBreachProcess(true)
        .processesChildrenData(null) // not assessed
        .hasConsentManager(false)
        .build();
  }

  @Test
  void javaEngineMatchesPythonGolden() throws Exception {
    Map<String, Object> report =
        DpiaEngine.buildDpiaReport(
            knownInput(), knownContext(), "2026-07-03T00:00:00Z", "test period");

    JsonNode javaTree = MAPPER.valueToTree(report);

    JsonNode goldenTree;
    try (InputStream in =
        getClass().getResourceAsStream("/dpdpa/dpia-golden.json")) {
      assertNotNull(in, "golden resource /dpdpa/dpia-golden.json must be on the test classpath");
      goldenTree = MAPPER.readTree(in);
    }

    // JsonNode.equals compares structurally, independent of key order — a match proves parity.
    assertEquals(
        goldenTree,
        javaTree,
        "Java DpiaEngine output diverged from the Python golden. First divergence:\n"
            + firstDivergence(goldenTree, javaTree, "$"));
  }

  /** Sanity assertions on the headline verdict so a failure is diagnosable at a glance. */
  @Test
  void headlineVerdictMatchesPython() {
    Map<String, Object> report =
        DpiaEngine.buildDpiaReport(knownInput(), knownContext(), "2026-07-03T00:00:00Z", "test period");
    @SuppressWarnings("unchecked")
    Map<String, Object> overall = (Map<String, Object>) report.get("overall");
    assertEquals("non_compliant", overall.get("compliance_status"));
    assertEquals(9, overall.get("total_gaps"));
    @SuppressWarnings("unchecked")
    Map<String, Object> byStatus = (Map<String, Object>) overall.get("activities_by_status");
    assertEquals(1, byStatus.get("compliant"));
    assertEquals(1, byStatus.get("attention"));
    assertEquals(1, byStatus.get("non_compliant"));
  }

  /** Best-effort locator of the first structural difference, to make failures actionable. */
  private static String firstDivergence(JsonNode a, JsonNode b, String path) {
    if (a.equals(b)) {
      return "(no divergence)";
    }
    if (a.isObject() && b.isObject()) {
      java.util.Iterator<String> names = a.fieldNames();
      while (names.hasNext()) {
        String n = names.next();
        if (!b.has(n)) {
          return path + "." + n + " missing in Java output";
        }
        if (!a.get(n).equals(b.get(n))) {
          return firstDivergence(a.get(n), b.get(n), path + "." + n);
        }
      }
      java.util.Iterator<String> bn = b.fieldNames();
      while (bn.hasNext()) {
        String n = bn.next();
        if (!a.has(n)) {
          return path + "." + n + " extra in Java output";
        }
      }
    }
    if (a.isArray() && b.isArray()) {
      if (a.size() != b.size()) {
        return path + " array size " + a.size() + " (golden) vs " + b.size() + " (java)";
      }
      for (int i = 0; i < a.size(); i++) {
        if (!a.get(i).equals(b.get(i))) {
          return firstDivergence(a.get(i), b.get(i), path + "[" + i + "]");
        }
      }
    }
    return path + ": golden=" + a + " java=" + b;
  }
}
